"""adding Chart of Accounts Table

Revision ID: 84e3cca9a0b6
Revises: 3e05ead33a34
Create Date: 2024-06-06 10:37:35.386216

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '84e3cca9a0b6'
down_revision = '3e05ead33a34'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.create_table('chart_of_accounts',
    sa.Column('id', sa.Integer(), nullable=False),
    sa.Column('name', sa.String(), nullable=False),
    sa.Column('account_type', sa.String(), nullable=True),
    sa.PrimaryKeyConstraint('id')
    )
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_table('chart_of_accounts')
    # ### end Alembic commands ###
